#!/usr/bin/php
<?php
set_include_path(get_include_path() . PATH_SEPARATOR . realpath(dirname(__FILE__)));

require 'lib/Zend/Exception.php';
require 'lib/Zend/Config.php';
require 'lib/Zend/Config/Exception.php';
require 'lib/Zend/Config/Ini.php';
require 'lib/Zend/Config/Writer.php';
require 'lib/Zend/Config/Writer/FileAbstract.php';
require 'lib/Zend/Config/Writer/Ini.php';

$loader = require 'vendor/autoload.php';

$loader->add('Judge', __DIR__.'/src');
$loader->add('Netresearch', __DIR__.'/lib');

// add plugin namespaces dynamically
$pluginDirs = glob(__DIR__.'/plugins/*', GLOB_ONLYDIR);
foreach ($pluginDirs as $path) {
    $loader->add(basename($path), dirname($path));
}

use Symfony\Component\Console\Application;

$console = new Application('Judge', '0.1');
$console->add(new Judge\Evaluate());
$console->run();
